(function(){
'use strict';
const M=AIECModel,C=JSON.parse(document.getElementById('aiec-contract').textContent),$=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let doc=null,view='',dirty=false,origin='',evaluation=null,lastDownload='';
const actualAnchors=new Map();
const current=()=>doc.periods.find(p=>p.period===view);
const editable=()=>doc&&view===doc.periods.at(-1).period&&current().stage==='draft';
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');};
const fmt=v=>{if(v===null||v===undefined)return 'onbekend';const m=typeof v==='string'?v.match(/^(-?)(\d+)(?:\.(\d+))?$/):null;return m?m[1]+BigInt(m[2]).toLocaleString('nl-BE')+(m[3]?','+m[3]:''):Number(v).toLocaleString('nl-BE',{maximumFractionDigits:1});};
const pct=(v,d)=>v===null||v===undefined?null:Number(v)*100/Number(d);
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
// No native confirm(): embedded viewers may block dialogs silently. Act at once and offer an undo.
function undoable(text,restore){message(text);const b=document.createElement('button');b.type='button';b.className='undo';b.textContent='Ongedaan maken';b.onclick=()=>{restore();message('Ongedaan gemaakt.');};$('message').append(' ',b);}
function healthOptions(value){return '<option value="">Kies een vlag</option>'+C.health.map(h=>'<option value="'+h.value+'"'+(value===h.value?' selected':'')+'>'+esc(h.symbol+' '+h.label)+'</option>').join('')+(value&&!C.health.some(h=>h.value===value)?'<option selected value="'+esc(value)+'">Onbekende keuze: '+esc(value)+'</option>':'');}
function statusOptions(value){const values=['Backlog','Bezig','Opgeleverd','Gepauzeerd'];if(value&&!values.includes(value))values.push(value);return '<option value="">Kies voortgang</option>'+values.map(v=>'<option'+(v===value?' selected':'')+'>'+esc(v)+'</option>').join('');}
function load(value,name='Projectbestand',converted=false){const migrated=converted||value.version===1,candidate=M.upgrade(value,C);if(dirty&&!confirm('De geopende werkmap bevat wijzigingen. Vervangen? Controleer eerst of je download echt bewaard is.'))return false;doc=candidate;view=doc.periods.at(-1).period;origin=name;dirty=migrated;lastDownload='';actualAnchors.clear();render();message(migrated?'Oud projectbestand veilig omgezet naar versie 2. De oorspronkelijke meetbasis en eerdere cijfers zijn behouden. Bewaar een nieuwe kopie; het oude bestand is niet gewijzigd.':'Werkmap geopend. Bewaar wijzigingen met de downloadknop.');return true;}
function changed(){dirty=true;updateComputed();}
function render(){
 actualAnchors.clear();
 $('welcome').hidden=!!doc;$('workspace').hidden=!doc;$('save-file').disabled=!doc;if(!doc)return;
 $('project-key').textContent=doc.project.key;$('project-name').textContent=doc.project.name;
 $('fixture-notice').hidden=!/fictief/i.test(doc.project.name+' '+doc.baseline.source);
 $('view-period').innerHTML=doc.periods.map(p=>'<option value="'+p.period+'"'+(p.period===view?' selected':'')+'>'+p.period+' · '+({draft:'werkmaand',closed:'lokaal afgesloten',published:'gepubliceerd'}[p.stage])+'</option>').join('');
 const active=editable(),p=current();$('auto-remaining').checked=doc.settings.auto_remaining;$('auto-remaining').disabled=!active;$('history-notice').hidden=active;$('history-notice').textContent=p.stage==='published'?'Gepubliceerde maand: alleen lezen.':'Lokaal afgesloten maand: alleen lezen, nog geen bewijs van publicatie.';
 $('project-health').innerHTML=healthOptions(p.inputs.vlag);$('project-health').disabled=!active;
 $('add-scope').disabled=!active;renderTexts(p,active);
 $('next-month').disabled=view!==doc.periods.at(-1).period;
 const prev=doc.periods[doc.periods.findIndex(x=>x.period===view)-1];
 $('milestones').querySelector('tbody').innerHTML=p.inputs.milestones.map(r=>{const old=prev?.inputs.milestones.find(x=>M.id(x.nr)===M.id(r.nr));const disabled=active?'':' disabled';const oldValue=field=>old?'Vorige: '+esc(M.blank(old[field])?'onbekend':old[field])+' md':'Nog geen vorige maand';const input=(field)=>'<input data-nr="'+r.nr+'" data-field="'+field+'" aria-label="Milestone '+r.nr+' '+field.replace('_md','')+'" inputmode="decimal" value="'+esc(r[field])+'"'+disabled+'><small class="previous">'+oldValue(field)+'</small>'+(field==='remaining_md'?'<small class="auto-note" data-auto-note="'+r.nr+'"></small>':'');const reason=(p.tracking.corrections||[]).find(x=>x.nr===r.nr)?.reason||'';
 return '<tr data-row="'+r.nr+'"><td class="milestone-name"><small>Milestone '+r.nr+'</small><strong>'+esc(r.milestone)+'</strong></td><td><select data-nr="'+r.nr+'" data-field="status" aria-label="Milestone '+r.nr+' voortgang"'+disabled+'>'+statusOptions(r.status)+'</select></td><td>'+input('actual_md')+'</td><td>'+input('remaining_md')+'</td><td><output class="computed" data-baseline="'+r.nr+'">—</output></td><td><output class="computed" data-expected="'+r.nr+'">—</output></td><td><output class="computed" data-ratio="'+r.nr+'">—</output></td><td><select data-nr="'+r.nr+'" data-field="gezondheid" aria-label="Milestone '+r.nr+' gezondheid"'+disabled+'>'+healthOptions(r.gezondheid)+'</select></td><td><textarea data-nr="'+r.nr+'" data-field="notities" aria-label="Milestone '+r.nr+' notitie" rows="1"'+disabled+'>'+esc(r.notities)+'</textarea><label class="correction-label" data-correction="'+r.nr+'"'+(needsCorrection(r.nr)?'':' hidden')+'>Actual gedaald: geef de reden<input class="correction" data-nr="'+r.nr+'" data-field="correction" aria-label="Milestone '+r.nr+' correctiereden" value="'+esc(reason)+'"'+disabled+'></label></td></tr>';}).join('');
 renderBasis();renderPlanning();updateComputed();
}
// The correction reason only matters when cumulative Actual drops below the previous month, or one was already given.
function needsCorrection(n){const i=doc.periods.findIndex(x=>x.period===view),p=doc.periods[i],row=p.inputs.milestones.find(r=>M.id(r.nr)===M.id(n)),old=doc.periods[i-1]?.inputs.milestones.find(r=>M.id(r.nr)===M.id(n));if((p.tracking.corrections||[]).some(c=>M.id(c.nr)===M.id(n)))return true;try{const now=M.decimal(row?.actual_md),before=M.decimal(old?.actual_md);return now!==null&&before!==null&&M.compare(now,before)<0;}catch{return false;}}
function updateComputed(){if(!doc)return;try{evaluation=M.evaluate(doc,C);}catch(e){evaluation={baseline:doc.baseline,states:[{period:view,rows:[],metrics:null,errors:[e.message],notes:[]}]};}
 const p=current(),s=evaluation.states.find(x=>x.period===view)||{errors:['Een eerdere maand bevat fouten. Herstel de oorspronkelijke werkmap of laat ze reviewen.'],rows:[],metrics:null,notes:[]};
 $('saved-state').textContent=(dirty?(lastDownload===JSON.stringify(doc)?'Download aangeboden — controleer het bestand op schijf':'Gewijzigd — nog niet opnieuw gedownload'):'Niet gewijzigd sinds openen')+(origin?' · '+origin:'');
 for(const el of document.querySelectorAll('[data-baseline]')){const r=s.rows.find(r=>r.nr===Number(el.dataset.baseline));el.textContent=r?fmt(r.baseline_md):'onbekend';}
 for(const el of document.querySelectorAll('[data-expected]')){const r=s.rows.find(r=>r.nr===Number(el.dataset.expected));el.textContent=r?fmt(r.expected_md):'onbekend';}
 for(const el of document.querySelectorAll('[data-ratio]')){const r=s.rows.find(r=>r.nr===Number(el.dataset.ratio));el.textContent=!r?'onbekend':r.backlog?'— (backlog)':r.expected_md===null||Number(r.baseline_md)===0?'onbekend':ratioText(Number(r.expected_md)/Number(r.baseline_md));}
 $('checks').classList.toggle('problem',!!s.errors.length);$('checks-title').textContent=s.errors.length?'Eerst nakijken':'Cijfercontroles in orde';$('check-list').innerHTML=s.errors.map(t=>'<li>'+esc(t)+'</li>').join('');$('notes').innerHTML=s.notes.map(t=>'<p>'+esc(t)+'</p>').join('');
 const m=s.metrics;$('scope-reading').textContent=m?fmt(pct(m.delivered_md,m.scope_denominator_md))+'%':'—';$('scope-detail').textContent=m?'Goedgekeurd '+fmt(pct(m.approved_md,m.scope_denominator_md))+'% · '+fmt(pct(Number(m.approved_md)-Number(m.delivered_md),m.scope_denominator_md))+' procentpunt nog open':'Geen betrouwbare stand zolang de invoer ongeldig is.';
 $('effort-reading').textContent=m?fmt(pct(m.actual_md,m.budget_md))+(m.actual_md===null?'':'%'):'—';$('effort-detail').textContent=m?(m.actual_md===null?'Onbekende Actual wordt niet als nul geteld.':fmt(m.actual_md)+' md van '+fmt(m.budget_md)+' md startbudget'):'Geen betrouwbare stand zolang de invoer ongeldig is.';
 updatePlanningSummary(s);drawCharts();
}
const ratioText=v=>v===null||v===undefined?'onbekend':v.toLocaleString('nl-BE',{minimumFractionDigits:2,maximumFractionDigits:2});
function renderPlanning(){const p=current(),active=editable(),choice=p.tracking.future_factor;$('future-factor-mode').value=choice===undefined||choice===null?'1':choice==='ratio'?'ratio':'custom';$('future-factor-value').value=$('future-factor-mode').value==='custom'?String(choice):'';$('future-factor-custom').hidden=$('future-factor-mode').value!=='custom';$('future-factor-mode').disabled=$('future-factor-value').disabled=!active;$('planning-period-note').textContent='Inzet ná '+p.period+'. Deze planning hoort bij deze rapportmaand; eerdere rapportplanningen blijven behouden.';for(const key of ['planning-add','planning-original'])$(key).disabled=!active;const disabled=active?'':' disabled';$('future-planning').querySelector('tbody').innerHTML='<tr class="reported"><td>'+esc(p.period)+' <small>(rapportmaand)</small></td><td><output id="period-actual">—</output> <small>gepresteerd</small></td><td><output id="period-total">—</output></td><td><output id="period-open">—</output></td><td></td></tr>'+(p.planning===null?'<tr><td colspan="5">Geen bijgestelde maandplanning in deze stand opgeslagen.</td></tr>':p.planning.map((r,i)=>'<tr><td><input type="month" data-plan-index="'+i+'" data-plan-field="period" value="'+esc(r.period)+'" aria-label="Planmaand '+(i+1)+'"'+disabled+'></td><td><input inputmode="decimal" data-plan-index="'+i+'" data-plan-field="effort_md" value="'+esc(r.effort_md)+'" aria-label="Inzet planmaand '+(i+1)+'"'+disabled+'></td><td><output data-plan-total="'+i+'">—</output></td><td><output data-plan-open="'+i+'">—</output></td><td>'+(active?'<button data-remove-plan="'+i+'" aria-label="Verwijder planmaand '+(i+1)+'">Verwijderen</button>':'')+'</td></tr>').join(''));}
function updatePlanningSummary(state){const p=current(),summary=state.planning_summary;$('period-actual').textContent=fmt(state.period_actual_md);$('period-total').textContent=fmt(state.metrics?.actual_md);$('period-open').textContent=fmt(state.metrics?M.projectedRemaining(state):null);const totals=new Map(),open=new Map();for(const r of M.forwardProjection(state.planning,state)){totals.set(r.period,r.total_md);open.set(r.period,r.open_md);}$('effort-ratio').textContent='Gemeten verwacht/Baseline (opgeleverd + lopend): '+ratioText(state.effort_ratio)+' · factor in projectie: '+ratioText(state.future_factor)+(state.future_factor!==undefined&&state.future_factor!==1?' · open werk in projectie: '+fmt(M.projectedRemaining(state))+' md':'');for(const el of document.querySelectorAll('[data-plan-open]'))el.textContent=fmt(open.get(p.planning?.[Number(el.dataset.planOpen)]?.period));for(const el of document.querySelectorAll('[data-plan-total]'))el.textContent=fmt(totals.get(p.planning?.[Number(el.dataset.planTotal)]?.period));$('planning-summary').classList.toggle('plan-warning',!!summary&&summary.difference_md!==null&&summary.difference_md!=='0');$('planning-summary').textContent=summary?'Komende inzet: '+fmt(summary.planned_remaining_md)+' md · Remaining volgens milestones: '+fmt(summary.remaining_md)+' md · Verschil: '+fmt(summary.difference_md)+' md · Eindstand volgens deze planning: '+fmt(summary.end_total_md)+' md.':'Geen volledig berekenbare resterende planning. Vul bedragen per maand in; onbekend wordt niet als nul opgeteld.';}
function runs(values){const out=[];let segment=[];values.forEach((v,i)=>{if(v===null){if(segment.length)out.push(segment);segment=[];}else segment.push([i,v]);});if(segment.length)out.push(segment);return out;}
function graphData(){const base=evaluation.baseline,plan=new Map(base.plan.map(p=>[p.period,p]));const selectedState=evaluation.states.find(s=>s.period===view),selectedPlan=selectedState?.planning||[];
 // The x-axis stops once everything is delivered: at the report month when done, else when the planned effort reaches the approved scope.
 const projection=M.forwardProjection(selectedState?.planning,selectedState),approvedMd=Number(selectedState?.metrics?.approved_md),reached=projection.find(r=>r.scope_md!==null&&r.scope_md>=approvedMd-1e-9);
 const end=selectedState?.metrics?.done?view:reached?[view,reached.period].sort().at(-1):[base.plan.at(-1).period,view,...selectedPlan.map(r=>r.period)].sort().at(-1),start=base.plan[0].period,lead=(+start.slice(5)===1?String(+start.slice(0,4)-1).padStart(4,'0')+'-12':start.slice(0,5)+String(+start.slice(5)-1).padStart(2,'0')),periods=M.months(lead,end);const states=new Map(evaluation.states.filter(s=>s.period<=view&&s.metrics).map(s=>[s.period,s]));const total=Number(M.add(...base.milestones.map(r=>r.planned_md))),budget=Number(base.budget_md);const selected=evaluation.states.find(s=>s.period===view),changes=selected?.scope_changes||[...states.values()].at(-1)?.scope_changes||[];
 const result={periods,asOf:view,reported:periods.map(m=>m===lead||doc.periods.some(p=>p.period===m)&&m<=view),planScope:periods.map(m=>plan.has(m)?Number(plan.get(m).scope_md)*100/total:null),planEffort:periods.map(m=>plan.has(m)?Number(plan.get(m).effort_md)*100/budget:null)};
 for(const [key,field,denominator] of [['delivered','delivered_md',total],['estimated','estimated_md',total],['assumed','assumed_md',total],['actual','actual_md',budget]])result[key]=periods.map(m=>states.has(m)?pct(states.get(m).metrics[field],denominator):null);
 // One month before the plan starts, at 0%: the first measurement then reads as a line from zero.
 for(const k of ['planScope','planEffort','delivered','actual'])if(result[k][0]===null)result[k][0]=0;
 result.approved=periods.map(m=>100+changes.filter(c=>c.month<=m).reduce((sum,c)=>sum+c.milestones.reduce((v,r)=>v+Number(r.weight_md),0),0)*100/total);
 const futureValues=new Map();let cumulative=selected?.metrics?.actual_md??null;if(selectedPlan.length)futureValues.set(view,cumulative);for(const row of selectedPlan){cumulative=cumulative===null?null:M.add(cumulative,row.effort_md);futureValues.set(row.period,cumulative);}result.forward=periods.map(p=>pct(futureValues.get(p)??null,budget));
 const expected=new Map();for(const r of M.forwardProjection(selected?.planning,selected))if(r.scope_md!==null)expected.set(r.period,r.scope_md);if(expected.size)expected.set(view,selected.metrics.estimated_md);result.expectedScope=periods.map(p=>expected.has(p)?Number(expected.get(p))*100/total:null);
 // A month without planned effort is zero effort: from the report month on, the projection runs flat to the end of the axis.
 const fill=(values,anchor)=>{const i=periods.indexOf(view);if(i<0||anchor===null)return values;const out=[...values];if(out[i]===null)out[i]=anchor;for(let k=i+1;k<out.length;k++)if(out[k]===null)out[k]=out[k-1];return out;};
 if(selected?.planning!=null&&selected.metrics){result.forward=fill(result.forward,pct(selected.metrics.actual_md,budget));result.expectedScope=fill(result.expectedScope,selected.metrics.estimated_md===null?null:Number(selected.metrics.estimated_md)*100/total);}
 // Show the plan-based lines only when they deviate from the original plan somewhere.
 const deviates=(values,plan)=>values.some((v,i)=>v!==null&&(plan[i]===null||Math.abs(v-plan[i])>=0.05));if(!deviates(result.forward,result.planEffort))result.forward=result.forward.map(()=>null);if(!deviates(result.expectedScope,result.planScope))result.expectedScope=result.expectedScope.map(()=>null);
 const scale=keys=>Math.max(140,Math.ceil((Math.max(100,...keys.flatMap(k=>result[k].filter(v=>v!==null)))+10)/20)*20);result.yMaxScope=scale(['planScope','delivered','estimated','assumed','approved','expectedScope']);result.yMaxEffort=scale(['planEffort','actual','forward']);return result;
}
function drawCharts(){let data;try{data=graphData();}catch(e){for(const kind of ['scope','effort'])$(kind+'-chart').textContent='Grafiek wacht op geldige meetbasis.';return;}
 for(const kind of ['scope','effort']){const isScope=kind==='scope',el=$(kind+'-chart'),W=Math.max(250,Math.floor(el.clientWidth)),H=310,L=58,R=20,T=22,B=39,PW=W-L-R,PH=H-T-B,count=data.periods.length,x=i=>L+(count>1?i/(count-1):.5)*PW,yMax=isScope?data.yMaxScope:data.yMaxEffort,y=v=>T+PH-v/yMax*PH,f=n=>Number(n.toFixed(2));
 const future=data.periods.some(m=>m>view),missing=data.periods.some((m,i)=>m<=view&&!data.reported[i]),assumed=isScope&&data.assumed.some(v=>v!==null);
 const legend=[['plan','Plan (oorspronkelijk)'],['delivered',isScope?'Opgeleverd':'Werkelijk besteed'],...(!isScope&&data.forward.some(v=>v!==null)?[['forward','Actuele inzetplanning']]:[]),...(isScope?[['estimated','Opgeleverd incl. lopend'],['approved','Goedgekeurde scope']]:[]),...(isScope&&data.expectedScope.some(v=>v!==null)?[['forward','Verwacht volgens inzetplanning']]:[]),...(future?[['future','Na peildatum']]:[]),...(missing?[['missing','Geen maandstand']]:[]),...(assumed?[['assumed','Aanname: volgens plan']]:[])];
 $(kind+'-legend').innerHTML=legend.map(([k,t])=>'<span class="legend-item"><span class="swatch '+k+'" aria-hidden="true"></span>'+t+'</span>').join('');
 const svg=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+(isScope?'Scope':'Inzet')+' tot '+view+'"><title>Live '+kind+'; ontbrekende maanden blijven gaten</title><defs><clipPath id="clip-'+kind+'"><rect x="'+(L-4)+'" y="'+(T-4)+'" width="'+(PW+8)+'" height="'+(PH+8)+'"/></clipPath><pattern id="missing-'+kind+'" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="6" height="6" fill="#f7f9fc"/><path d="M0 0V6" stroke="#cfd5dd"/></pattern></defs>'];
 const firstFuture=data.periods.findIndex(m=>m>view);if(firstFuture>=0){const a=firstFuture>0?x(firstFuture-1):L;svg.push('<rect x="'+f(a)+'" y="'+T+'" width="'+f(W-R-a)+'" height="'+PH+'" fill="#f7f9fc"/>');}
 data.periods.forEach((m,i)=>{if(m<=view&&!data.reported[i]){const w=PW/Math.max(1,count-1)*.46,a=Math.max(L,x(i)-w/2);svg.push('<rect x="'+f(a)+'" y="'+T+'" width="'+f(Math.min(W-R-a,w))+'" height="'+PH+'" fill="url(#missing-'+kind+')"/>');}});
 const plan=isScope?data.planScope:data.planEffort;runs(plan).forEach(s=>{if(s.length>1)svg.push('<polygon points="'+s.map(([i,v])=>f(x(i))+','+f(y(v+10))).concat([...s].reverse().map(([i,v])=>f(x(i))+','+f(y(Math.max(0,v-10))))).join(' ')+'" fill="#ecf6ee"/>');});
 const step=20*Math.max(1,Math.ceil(yMax/140));for(let tick=0;tick<=yMax;tick+=step){svg.push('<path d="M'+L+' '+f(y(tick))+'H'+(W-R)+'" stroke="#eceff4"/><text x="'+(L-7)+'" y="'+f(y(tick)+3)+'" text-anchor="end" font-size="10" fill="#687483">'+(tick>=10000?tick.toExponential(1):fmt(tick))+'%</text>');}
 const stride=Math.max(1,Math.ceil(count/Math.max(2,Math.floor(PW/53)))),indices=[];for(let i=0;i<count;i+=stride)indices.push(i);if(indices.at(-1)!==count-1){if(count-1-indices.at(-1)<stride)indices.pop();indices.push(count-1);}indices.forEach(i=>svg.push('<text x="'+f(x(i))+'" y="'+(H-15)+'" text-anchor="middle" font-size="10" fill="#687483">'+data.periods[i].slice(5)+'/'+data.periods[i].slice(2,4)+'</text>'));
 function plot(values,name,color,dotted=false,open=false,ring=false){svg.push('<g id="form-'+kind+'-'+name+'" clip-path="url(#clip-'+kind+')">');runs(values).forEach(s=>{if(s.length>1)svg.push('<path d="'+s.map(([i,v],j)=>(j?'L':'M')+f(x(i))+' '+f(y(v))).join(' ')+'" fill="none" stroke="'+color+'" stroke-width="2.3" stroke-linecap="round"'+(dotted?' stroke-dasharray="1.5 5"':'')+'/>');s.forEach(([i,v])=>svg.push('<circle cx="'+f(x(i))+'" cy="'+f(y(v))+'" '+(ring?'r="'+(ring===true?6:4.8)+'" fill="none" stroke-width="'+(ring===true?2.3:1.8)+'"':'r="3" fill="'+(open?'#ffffff':color)+'"')+' stroke="'+color+'"><title>'+data.periods[i]+' · '+name+' '+fmt(v)+'%</title></circle>'));});svg.push('</g>');}
 if(isScope){let path='M'+f(x(0))+' '+f(y(data.approved[0]));for(let i=1;i<count;i++)path+='H'+f(x(i))+'V'+f(y(data.approved[i]));svg.push('<path id="form-scope-approved" d="'+path+'" fill="none" stroke="#278e93" stroke-width="1.6" stroke-dasharray="6 4"/>');plot(data.expectedScope,'expected','#9f5804',true,true);plot(data.assumed,'assumed','#8695a8',true,true);}if(!isScope)plot(data.forward,'forward','#9f5804',true,true);plot(plan,'plan','#333332');if(isScope)plot(data.estimated,'estimated','#0055cc',true,false,4.8);plot(isScope?data.delivered:data.actual,'actual','#0055cc',false,false,true);svg.push('</svg>');el.innerHTML=svg.join('');
 }
}
function renderBasis(){const p=current(),base=doc.baseline;let html='<p><strong>Oorspronkelijk budget:</strong> '+esc(base.budget_md)+' md. <strong>Bron:</strong> '+esc(base.source)+'</p><div class="table-scroll"><table><thead><tr><th>Nr</th><th>Oorspronkelijke milestone</th><th>Vast gewicht (md)</th></tr></thead><tbody>'+base.milestones.map(r=>'<tr><td>'+r.nr+'</td><td>'+esc(r.milestone)+'</td><td>'+esc(r.planned_md)+'</td></tr>').join('')+'</tbody></table></div><p>De meetbasis en eerdere maandstanden worden in dit scherm niet aangepast.</p>';
 const seen=new Set();for(const period of doc.periods.filter(x=>x.period<=view))for(const change of period.tracking.scope_changes||[]){if(seen.has(change.id))continue;seen.add(change.id);html+='<p><strong>'+esc(change.id)+'</strong> · '+esc(change.month)+' · '+esc(change.decision.by)+' · '+esc(change.decision.source)+'<br>'+change.milestones.map(r=>esc(r.nr+' '+r.milestone+' — '+r.weight_md+' md vast gewicht')).join('<br>')+'</p>';if(editable()&&period===p&&change.milestones.length===1)html+='<button data-edit-scope="'+esc(change.id)+'">Dit conceptbesluit corrigeren</button>';}
 $('basis').innerHTML=html;
}
function save(){if(!doc)return;try{M.validate(doc,C);const data=JSON.stringify(doc,null,2)+'\n',blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=doc.project.key+'_'+doc.periods.at(-1).period+'.aiec.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);lastDownload=JSON.stringify(doc);origin=a.download;updateComputed();message('Download gestart: '+a.download+'. Controleer je downloads; dit is de bewaarkopie.');}catch(e){message(e.message,true);}}
function example(){const values=[0,20,40,60,65,70,75,80,100];const base={budget_md:100,source:'Fictieve oorspronkelijke planning; duur 1/1/1/4/1 maanden.',milestones:[1,2,3,4,5].map(n=>({nr:n,milestone:'Milestone '+n,planned_md:20})),plan:values.map((v,i)=>({period:'2026-'+String(i+1).padStart(2,'0'),scope_md:v,effort_md:v}))};const periods=[];for(let index=0;index<=5;index++){let cursor=0;const rows=[1,1,1,4,1].map((duration,i)=>{const elapsed=Math.max(0,Math.min(index-cursor,duration)),actual=20*elapsed/duration;cursor+=duration;return {nr:i+1,milestone:'Milestone '+(i+1),status:elapsed===duration?'Opgeleverd':elapsed===0?'Backlog':'Bezig',actual_md:actual,remaining_md:20-actual,gezondheid:'op-schema',notities:''};});periods.push({period:'2026-'+String(index+1).padStart(2,'0'),inputs:{milestones:rows,vlag:'op-schema'},tracking:{},confirmed:index<5?[1,2,3,4,5]:[],stage:index<5?'closed':'draft',planning:M.baselineMonths(base,'2026-'+String(index+1).padStart(2,'0'))});}return {format:C.format,version:C.version,settings:{auto_remaining:true},project:{key:'POR-1',name:'Fictief voorbeeld — vijf gelijke milestones'},baseline:base,periods};}
function setupRow(){const n=$('setup-milestones').children.length+1;$('setup-milestones').insertAdjacentHTML('beforeend','<tr><td><input data-field="nr" aria-label="Nummer oorspronkelijke milestone" value="'+n+'" required></td><td><input data-field="milestone" aria-label="Naam oorspronkelijke milestone" required></td><td><input data-field="planned_md" aria-label="Geplande md milestone" inputmode="decimal" required></td><td><button type="button" data-remove-row aria-label="Verwijder onvastgelegde rij">✕</button></td></tr>');}
function setupPlan(){const last=$('setup-plan').lastElementChild?.querySelector('input')?.value;let when='';try{when=last?M.nextMonth(last):$('setup-period').value;}catch{}$('setup-plan').insertAdjacentHTML('beforeend','<tr><td><input data-field="period" aria-label="Planmaand" type="month" value="'+esc(when)+'" required></td><td><input data-field="effort_md" aria-label="Inzet in deze maand" inputmode="decimal" required></td><td><output class="setup-cumulative">—</output></td><td><button type="button" data-remove-row aria-label="Verwijder onvastgelegde planmaand">✕</button></td></tr>');setupTotals();}
function setupTotals(){let running='0';const totals=new Map();try{const parsed=M.normalizePlan(readRows('setup-plan'));if(parsed.errors.length)throw Error();for(const r of parsed.rows){running=M.add(running,r.effort_md);totals.set(r.period,running);}$('setup-total').textContent='Totaal maandinzet: '+fmt(running)+' md. Startbudget: '+($('setup-budget').value||'nog in te vullen')+' md.';}catch{$('setup-total').textContent='Vul de inzet per maand in; cumulatief wordt berekend.';}for(const row of $('setup-plan').children){row.querySelector('output').textContent=fmt(totals.get(row.querySelector('[data-field=period]').value));}}
function readRows(id){return [...$(id).children].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.value])));}
$('open-file').onclick=$('welcome-open').onclick=()=>$('file-input').click();
$('file-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>C.maxBytes)throw Error('Bestand is te groot.');const raw=await file.text(),candidate=M.parse(raw,C);load(candidate,file.name,JSON.parse(raw).version===1);}catch(error){message('Bestand niet geopend: '+error.message+' Je huidige werkmap is behouden.',true);}finally{e.target.value='';}};
$('save-file').onclick=save;$('demo').onclick=()=>{if(load(example(),'fictief voorbeeld')){dirty=true;updateComputed();}};
$('view-period').onchange=e=>{view=e.target.value;render();};
$('auto-remaining').onchange=e=>{if(editable()){doc.settings.auto_remaining=e.target.checked;actualAnchors.clear();changed();}};
$('project-health').onchange=e=>{if(editable()){current().inputs.vlag=e.target.value;changed();}};
function renderTexts(p,active){$('report-texts').innerHTML=C.texts.map(t=>'<label class="text-field">'+esc(t.title)+'<small>'+esc(t.prompt)+'</small><textarea data-text="'+t.id+'" rows="5"'+(active?'':' disabled')+'>'+esc(p.inputs[t.id]||'')+'</textarea><small data-lines="'+t.id+'"></small></label>').join('');C.texts.forEach(t=>lineHint(t));}
function lineHint(t){const n=(current().inputs[t.id]||'').split('\n').filter(x=>x.trim()).length,el=document.querySelector('[data-lines="'+t.id+'"]'),range=t.min_lines||t.max_lines?' · gevraagd '+(t.min_lines||1)+'–'+(t.max_lines||'…'):'',off=n>0&&(n<(t.min_lines||1)||(t.max_lines&&n>t.max_lines));el.textContent=(n?n+(n===1?' regel':' regels'):'Nog leeg; kan ook later via de portfolio-assistent')+range;el.classList.toggle('off',!!off);}
$('report-texts').addEventListener('input',e=>{const id=e.target.dataset.text;if(!editable()||!id)return;current().inputs[id]=e.target.value;lineHint(C.texts.find(t=>t.id===id));changed();});
function captureActual(n){const row=current().inputs.milestones.find(r=>r.nr===n),resolved=evaluation?.states.find(s=>s.period===view)?.rows.find(r=>r.nr===n);const anchor={actual:row.actual_md,remaining:resolved?.remaining_md??row.remaining_md};actualAnchors.set(n,anchor);return anchor;}
$('milestones').addEventListener('input',e=>{if(e.target.dataset.field!=='actual_md')return;const n=Number(e.target.dataset.nr);
 // Registered before the main handler: toggle after it has stored the new Actual.
 queueMicrotask(()=>{const label=document.querySelector('[data-correction="'+n+'"]');if(label)label.hidden=!needsCorrection(n);});});
$('milestones').addEventListener('focusin',e=>{if(editable()&&e.target.dataset.field==='actual_md')captureActual(Number(e.target.dataset.nr));});
$('milestones').addEventListener('input',e=>{
 const el=e.target;if(!editable()||!el.dataset.field)return;
 const p=current(),n=Number(el.dataset.nr),row=p.inputs.milestones.find(r=>r.nr===n),field=el.dataset.field,note=document.querySelector('[data-auto-note="'+n+'"]');
 {
  if(field==='correction'){p.tracking.corrections=(p.tracking.corrections||[]).filter(r=>r.nr!==n);if(el.value.trim())p.tracking.corrections.push({nr:n,reason:el.value});}
  else{
   if(field==='actual_md'){
    const anchor=actualAnchors.get(n)||captureActual(n);try{const coupled=M.coupledRemaining(anchor.actual,anchor.remaining,el.value,doc.settings.auto_remaining,C.tracking.delivered.includes(String(row.status).trim().toLowerCase()));if(coupled.changed){row.remaining_md=coupled.remaining;document.querySelector('[data-row="'+n+'"] [data-field=remaining_md]').value=coupled.remaining;}if(note)note.textContent=coupled.mode==='capped'?'Remaining op 0 begrensd: Actual overschrijdt het eerder verwachte totaal. Schat eventueel extra restwerk.':coupled.mode==='unknown'&&doc.settings.auto_remaining?'Niet gekoppeld: oude Actual of Remaining onbekend.':' ';}catch{if(note)note.textContent='Auto-calc wacht op een geldig getal; Remaining is behouden.';}
   }
   row[field]=el.value;if(['actual_md','remaining_md','status'].includes(field))delete row.baseline_md;
   if(field==='remaining_md'){actualAnchors.delete(n);if(note)note.textContent='';}
   if(field==='status'&&C.tracking.delivered.includes(el.value.toLowerCase().trim())){row.remaining_md=0;document.querySelector('[data-row="'+n+'"] [data-field=remaining_md]').value='0';actualAnchors.delete(n);}
  }
 }
 changed();
});
$('next-month').onclick=()=>{const p=doc.periods.at(-1);$('month-value').value=M.nextMonth(p.period);$('month-error').textContent='';$('month-dialog').showModal();};
$('month-form').onsubmit=e=>{e.preventDefault();try{doc=M.newPeriod(doc,$('month-value').value,C);view=doc.periods.at(-1).period;dirty=true;$('month-dialog').close();render();message('Nieuwe werkmaand gestart. Kijk de overgenomen waarden na en download je bijgewerkte projectbestand.');}catch(error){$('month-error').textContent=error.message;}};
$('new-project').onclick=()=>{$('setup-form').reset();$('setup-period').value=today();$('setup-milestones').innerHTML='';$('setup-plan').innerHTML='';setupRow();setupPlan();$('setup-error').textContent='';$('setup-dialog').showModal();};
$('setup-add-row').onclick=setupRow;$('setup-add-plan').onclick=setupPlan;
$('setup-form').addEventListener('input',setupTotals);
$('planning-add').onclick=()=>{if(!editable())return;try{const p=current(),rows=p.planning||[],last=rows.map(r=>r.period).filter(s=>/^\d{4}-(0[1-9]|1[0-2])$/.test(s)&&s>p.period).sort().at(-1)||p.period;const when=M.nextMonth(last);p.planning=rows;p.planning.push({period:when,effort_md:null});dirty=true;renderPlanning();updateComputed();}catch(e){message(e.message,true);}};
$('planning-original').onclick=()=>{if(!editable())return;const p=current(),original=M.baselineMonths(doc.baseline,p.period);if(JSON.stringify(p.planning||[])===JSON.stringify(original)){message('De resterende planning is al gelijk aan de oorspronkelijke planning.');return;}const before=M.copy(p.planning??null);p.planning=original;dirty=true;renderPlanning();updateComputed();undoable('Oorspronkelijke resterende planning overgenomen.',()=>{p.planning=before;dirty=true;renderPlanning();updateComputed();});};
$('future-planning').addEventListener('input',e=>{if(!editable()||e.target.dataset.planIndex===undefined)return;const i=Number(e.target.dataset.planIndex);current().planning[i][e.target.dataset.planField]=e.target.value;changed();});
$('future-planning').addEventListener('click',e=>{if(!editable()||e.target.dataset.removePlan===undefined)return;const i=Number(e.target.dataset.removePlan),p=current(),before=M.copy(p.planning),[removed]=p.planning.splice(i,1);dirty=true;renderPlanning();updateComputed();undoable('Planmaand '+(removed.period||'')+' verwijderd.',()=>{p.planning=before;dirty=true;renderPlanning();updateComputed();});});
$('setup-form').onsubmit=e=>{e.preventDefault();try{const base=M.baselineFromMonths($('setup-budget').value,readRows('setup-milestones'),readRows('setup-plan'),$('setup-source').value);const candidate={format:C.format,version:C.version,settings:{auto_remaining:true},project:{key:$('setup-key').value.trim(),name:$('setup-name').value},baseline:base,periods:[{period:$('setup-period').value,inputs:{milestones:base.milestones.map(r=>({nr:r.nr,milestone:r.milestone,status:'Backlog',actual_md:null,remaining_md:r.planned_md,gezondheid:'',notities:''})),vlag:''},tracking:{},confirmed:[],stage:'draft',planning:M.baselineMonths(base,$('setup-period').value)}]};if(candidate.periods[0].period<base.plan[0].period)throw Error('Rapportmaand ligt vóór de oorspronkelijke planning.');if(load(candidate,'nieuwe werkmap')){dirty=true;$('setup-dialog').close();updateComputed();message('Meetbasis vastgelegd in je lokale concept. Vul nu de werkelijke stand in; dit is nog geen goedkeuring of publicatie.');}}catch(error){$('setup-error').textContent=error.message;}};
function scopeDialog(change=null){$('scope-form').reset();$('scope-form').dataset.edit=change?.id||'';$('scope-nr').disabled=!!change;const p=current(),row=change? p.inputs.milestones.find(r=>r.nr===change.milestones[0].nr):null;$('scope-nr').value=change?row.nr:Math.max(...p.inputs.milestones.map(r=>r.nr))+1;$('scope-name').value=change?.milestones[0].milestone||'';$('scope-weight').value=change?.milestones[0].weight_md||'';$('scope-remaining').value=row?.remaining_md??'';$('scope-by').value=change?.decision.by||'';$('scope-date').value=change?.decision.date||'';$('scope-source').value=change?.decision.source||'';$('scope-error').textContent='';$('scope-dialog').showModal();}
$('add-scope').onclick=()=>{if(editable())scopeDialog();};
$('basis').onclick=e=>{if(e.target.dataset.editScope&&editable())scopeDialog((current().tracking.scope_changes||[]).find(c=>c.id===e.target.dataset.editScope));};
$('scope-form').onsubmit=e=>{e.preventDefault();try{const candidate=M.copy(doc),p=candidate.periods.at(-1),n=M.id($('scope-nr').value),edit=$('scope-form').dataset.edit;const weight=M.decimal($('scope-weight').value),remaining=M.decimal($('scope-remaining').value);if(!weight||!remaining||weight==='0'||remaining==='0')throw Error('Nieuwe scope vraagt positief gewicht en positieve Remaining.');const when=$('scope-date').value.slice(0,7);const change={id:edit||'scope-'+p.period+'-'+n,month:when,decision:{by:$('scope-by').value,date:$('scope-date').value,source:$('scope-source').value},milestones:[{nr:n,milestone:$('scope-name').value,weight_md:weight}]};p.tracking.scope_changes=(p.tracking.scope_changes||[]).filter(c=>c.id!==edit);p.tracking.scope_changes.push(change);if(edit){const row=p.inputs.milestones.find(r=>r.nr===n);row.milestone=change.milestones[0].milestone;row.remaining_md=remaining;delete row.baseline_md;}else p.inputs.milestones.push({nr:n,milestone:change.milestones[0].milestone,status:'Backlog',actual_md:null,remaining_md:remaining,gezondheid:'',notities:''});p.confirmed=p.confirmed.filter(x=>x!==n);const evaluated=M.evaluate(candidate,C),s=evaluated.states.at(-1);if(s.period!==p.period||!s.metrics)throw Error(s.errors.join(' '));doc=candidate;dirty=true;$('scope-dialog').close();render();message('Scopebesluit toegevoegd aan het concept. Controleer ook Actual en gezondheid van de nieuwe milestone.');}catch(error){$('scope-error').textContent=error.message;}};
document.addEventListener('click',e=>{if(e.target.dataset.close)$(e.target.dataset.close).close();if(e.target.hasAttribute('data-remove-row')){e.target.closest('tr').remove();setupTotals();}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
let resizeFrame;window.addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{if(doc)drawCharts();});});
$('future-factor-mode').onchange=e=>{if(!editable())return;const t=current().tracking;if(e.target.value==='1')delete t.future_factor;else if(e.target.value==='ratio')t.future_factor='ratio';else t.future_factor=$('future-factor-value').value||'1';renderPlanning();changed();};
$('future-factor-value').addEventListener('input',e=>{if(!editable())return;current().tracking.future_factor=e.target.value.trim()||'1';changed();});
window.AIECApp={getDocument:()=>doc?M.copy(doc):null,getEvaluation:()=>evaluation?M.copy(evaluation):null,load,example,contract:C};
render();
const preset=JSON.parse($('aiec-project').textContent);  // Set by `form open`: the project opens without a file dialog.
if(preset)load(preset,preset.project.key+'_'+preset.periods.at(-1).period+'.aiec.json');
})();
