/* Pure offline model. Raw input is retained; Python remains authoritative on import. */
(function(g){
'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
const blank=x=>x===null||x===undefined||(typeof x==='string'&&!x.trim());
const object=(v,allowed,required,label)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k))||required.some(k=>!Object.hasOwn(v,k)))throw Error(label+': ontbrekende of onbekende velden; niets verwijderen.');};
function decimal(v,label='Getal'){
 if(blank(v))return null;
 if(!['string','number'].includes(typeof v))throw Error(label+': verwacht een getal.');
 let s=String(v).trim().replace(',','.');if(s.length>60||!/^\d+(\.\d+)?$/.test(s))throw Error(label+': gebruik een niet-negatief getal (komma of punt).');
 let [a,b='']=s.split('.');a=a.replace(/^0+(?=\d)/,'');b=b.replace(/0+$/,'');return a+(b?'.'+b:'');
}
function parts(s){const [a,b='']=s.split('.');return [BigInt(a+b),b.length];}
function add(...values){let n=0n,k=0;for(const v of values){const [m,j]=parts(v);const z=Math.max(k,j);n=n*10n**BigInt(z-k)+m*10n**BigInt(z-j);k=z;}let s=n.toString().padStart(k+1,'0');return decimal(k?s.slice(0,-k)+'.'+s.slice(-k):s);}
function compare(a,b){let [n,i]=parts(a),[m,j]=parts(b);const k=Math.max(i,j);n*=10n**BigInt(k-i);m*=10n**BigInt(k-j);return n<m?-1:n>m?1:0;}
function subtract(a,b){let [n,i]=parts(a),[m,j]=parts(b);const k=Math.max(i,j);n=n*10n**BigInt(k-i)-m*10n**BigInt(k-j);if(n<0n)throw Error('Negatief verschil.');const s=n.toString().padStart(k+1,'0');return decimal(k?s.slice(0,-k)+'.'+s.slice(-k):s);}
function scaled(value,numerator,denominator){const [v,vs]=parts(value),[n,ns]=parts(numerator),[d,ds]=parts(denominator);const a=v*n*10n**BigInt(ds+28),b=d*10n**BigInt(vs+ns);let q=a/b;const r=a%b;if(r*2n>b||(r*2n===b&&q%2n))q++;const s=q.toString().padStart(29,'0');return decimal(s.slice(0,-28)+'.'+s.slice(-28));}
function coupledRemaining(oldActual,oldRemaining,newActual,enabled=true,done=false){if(!enabled||done)return {changed:false,mode:done?'delivered':'off',remaining:oldRemaining};let a,r;try{a=decimal(oldActual);r=decimal(oldRemaining);}catch{return {changed:false,mode:'unknown',remaining:oldRemaining};}const value=decimal(newActual);if(value===null||a===null||r===null)return {changed:false,mode:'unknown',remaining:oldRemaining};const target=add(a,r),over=compare(value,target)>0;return {changed:true,mode:over?'capped':'coupled',remaining:over?'0':subtract(target,value),target};}
function number(v,label,positive=false){const d=decimal(v,label);if(d===null||(positive&&compare(d,'0')<=0))throw Error(label+': '+(positive?'positief getal':'getal')+' vereist.');return d;}
function id(v){const d=number(v,'Milestonenummer',true);if(d.includes('.')||!Number.isSafeInteger(Number(d)))throw Error('Milestonenummer moet een veilig positief geheel getal zijn.');return Number(d);}
function month(s){if(typeof s!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(s)||s.slice(0,4)==='0000')throw Error('Maand: gebruik JJJJ-MM.');return s;}
function nextMonth(s){month(s);let [y,m]=s.split('-').map(Number);if(++m>12){m=1;y++;}if(y>9999)throw Error('Maand buiten bereik.');return String(y).padStart(4,'0')+'-'+String(m).padStart(2,'0');}
function months(a,b){month(a);month(b);const out=[];for(let s=a;s<=b;s=nextMonth(s)){out.push(s);if(out.length>1201)throw Error('Maandbereik te groot.');}if(!out.length)throw Error('Omgekeerd maandbereik.');return out;}
const text=(s,label)=>{if(typeof s!=='string'||!s.trim())throw Error(label+': tekst vereist.');return s;};
function baseline(v){object(v,['budget_md','source','milestones','plan'],['budget_md','source','milestones','plan'],'Meetbasis');const budget=number(v.budget_md,'Startbudget',true);text(v.source,'Bron van planning');if(!Array.isArray(v.milestones)||!v.milestones.length)throw Error('Oorspronkelijke milestones ontbreken.');let ids=new Set();const rows=v.milestones.map(r=>{object(r,['nr','milestone','planned_md'],['nr','milestone','planned_md'],'Baseline-milestone');const n=id(r.nr);if(ids.has(n))throw Error('Dubbel nummer in meetbasis.');ids.add(n);return {nr:n,milestone:text(r.milestone,'Naam milestone'),planned_md:number(r.planned_md,'Plan (md)')};});const total=add(...rows.map(r=>r.planned_md));if(compare(total,'0')<=0)throw Error('Oorspronkelijke scope moet positief zijn.');if(!Array.isArray(v.plan)||!v.plan.length)throw Error('Vul de expliciete maandplanning in.');ids=new Set();const plan=v.plan.map(p=>{object(p,['period','scope_md','effort_md'],['period','scope_md','effort_md'],'Planpunt');month(p.period);if(ids.has(p.period))throw Error('Dubbele planmaand.');ids.add(p.period);return {period:p.period,scope_md:number(p.scope_md,'Plan scope'),effort_md:number(p.effort_md,'Plan inzet')};}).sort((a,b)=>a.period.localeCompare(b.period));for(const [field,end] of [['scope_md',total],['effort_md',budget]]){let previous='0';for(const p of plan){if(compare(p[field],previous)<0)throw Error('Maandplanning moet oplopen.');previous=p[field];}if(compare(previous,end)!==0)throw Error('Laatste planmaand moet op volledige scope en budget eindigen.');}months(plan[0].period,plan.at(-1).period);return {budget_md:budget,source:v.source,milestones:rows.sort((a,b)=>a.nr-b.nr),plan};}
function planShape(rows){if(rows===null)return;if(!Array.isArray(rows)||rows.length>1200)throw Error('Maandplanning moet een lijst zijn.');for(const r of rows){object(r,['period','effort_md'],['period','effort_md'],'Planmaand');if(typeof r.period!=='string'||(r.effort_md!==null&&!['string','number'].includes(typeof r.effort_md)))throw Error('Ongeldige planmaand.');}}
function normalizePlan(rows,after=null){planShape(rows);if(rows===null)return {rows:null,errors:[]};const out=[],errors=[],seen=new Set();for(const r of rows){let value=null;try{month(r.period);if(after&&r.period<=after)throw Error('Resterende planning moet na de rapportmaand liggen: '+r.period);if(seen.has(r.period))throw Error('Dubbele planmaand: '+r.period);seen.add(r.period);}catch(e){errors.push(e.message);}try{value=number(r.effort_md,'Inzet '+r.period);}catch(e){errors.push(e.message);}out.push({period:r.period,effort_md:value});}return {rows:out.sort((a,b)=>a.period.localeCompare(b.period)),errors};}
function baselineMonths(base,after){base=baseline(base);let previous=null,before='0';const out=[];for(const p of base.plan){const [y,m]=p.period.split('-').map(Number),index=y*12+m,known=previous===null||index===previous+1;if(p.period>after)out.push({period:p.period,effort_md:known?subtract(p.effort_md,before):null});previous=index;before=p.effort_md;}return out;}
function futurePlan(base,after,previous=null){return previous===null?baselineMonths(base,after):copy(previous.filter(r=>r.period>after));}
function baselineFromMonths(budget,milestones,monthly,source){budget=number(budget,'Startbudget',true);const rows=milestones.map(r=>{object(r,['nr','milestone','planned_md'],['nr','milestone','planned_md'],'Milestone');return {nr:id(r.nr),milestone:text(r.milestone,'Milestone'),planned_md:number(r.planned_md,'Oorspronkelijk plan')};});const total=add(...rows.map(r=>r.planned_md)),parsed=normalizePlan(monthly);if(parsed.errors.length)throw Error(parsed.errors.join(' '));if(!parsed.rows.length)throw Error('Voer minstens één planmaand in.');let cumulative='0';const plan=parsed.rows.map(r=>{cumulative=add(cumulative,r.effort_md);return {period:r.period,effort_md:cumulative,scope_md:compare(cumulative,budget)===0?total:scaled(cumulative,total,budget)};});return baseline({budget_md:budget,source,milestones:rows,plan});}
function upgrade(doc,c){validate(doc,c);const result=copy(doc);for(const p of result.periods)for(const row of p.inputs.milestones)delete row.forecast_md;if(result.version===1){result.version=2;result.settings={auto_remaining:true};for(const p of result.periods)p.planning=null;const p=result.periods.at(-1);if(p.stage==='draft')p.planning=baselineMonths(result.baseline,p.period);}return validate(result,c);}
function trackingShape(v){if(!Array.isArray(v.scope_changes??[]))throw Error('Scopebesluiten moeten een lijst zijn.');if(v.scope_changes===null)throw Error('Scopebesluiten moeten een lijst zijn.');for(const change of v.scope_changes||[]){object(change,['id','month','decision','milestones'],['id','month','decision','milestones'],'Scopebesluit');text(change.id,'Besluit-id');if(typeof change.month!=='string')throw Error('Ongeldige besluitmaand.');object(change.decision,['by','date','source'],['by','date','source'],'Beslissing');if(Object.values(change.decision).some(x=>typeof x!=='string'))throw Error('Beslissing vraagt tekstvelden.');if(!Array.isArray(change.milestones)||!change.milestones.length)throw Error('Scopebesluit vraagt milestones.');for(const row of change.milestones){object(row,['nr','milestone','weight_md'],['nr','milestone','weight_md'],'Scopemilestone');if(!Number.isSafeInteger(row.nr)||row.nr<1||typeof row.milestone!=='string'||(row.weight_md!==null&&!['number','string'].includes(typeof row.weight_md)))throw Error('Ongeldige scopemilestone.');}}if(!Array.isArray(v.corrections??[])||v.corrections===null)throw Error('Correcties moeten een lijst zijn.');for(const r of v.corrections||[]){object(r,['nr','reason'],['nr','reason'],'Correctie');if(!Number.isSafeInteger(r.nr)||typeof r.reason!=='string')throw Error('Ongeldige correctie.');}if(Object.hasOwn(v,'legacy_ack')){object(v.legacy_ack,['pages','reason'],['pages','reason'],'Meetstart');if(!Array.isArray(v.legacy_ack.pages)||v.legacy_ack.pages.some(x=>typeof x!=='string')||typeof v.legacy_ack.reason!=='string')throw Error('Ongeldige meetstart.');}if(Object.hasOwn(v,'assume_on_plan')&&typeof v.assume_on_plan!=='boolean')throw Error('Ongeldige aannamekeuze.');if(Object.hasOwn(v,'future_factor')&&!(v.future_factor==='ratio'||(['number','string'].includes(typeof v.future_factor)&&v.future_factor!=='')))throw Error('Ongeldige factor voor toekomstig werk.');}
function validate(doc,c){const v2=doc?.version===2,fields=['format','version','project','baseline','periods',...(v2?['settings']:[])];object(doc,fields,fields,'Projectbestand');if(doc.format!==c.format||![1,c.version].includes(doc.version))throw Error('Onbekende bestandsversie; gebruik een passende formulierupdate.');if(new TextEncoder().encode(JSON.stringify(doc)).length>c.maxBytes)throw Error('Bestand is te groot.');if(v2){object(doc.settings,['auto_remaining'],['auto_remaining'],'Instellingen');if(typeof doc.settings.auto_remaining!=='boolean')throw Error('Auto-calc moet aan of uit zijn.');}object(doc.project,['key','name'],['key','name'],'Project');if(!/^[A-Z][A-Z0-9_]*-\d+(-intern-\d+)?$/.test(doc.project.key))throw Error('Projectkey: bijvoorbeeld POR-123, of AI-49-intern-1 voor een intern project.');text(doc.project.name,'Projectnaam');baseline(doc.baseline);if(!Array.isArray(doc.periods)||!doc.periods.length||doc.periods.length>1200)throw Error('Ongeldig aantal maanden.');let previous='';doc.periods.forEach((p,index)=>{const fields=['period','inputs','tracking','confirmed','stage',...(v2?['planning']:[])];object(p,[...fields,'published_hash'],fields,'Maand');if(v2)planShape(p.planning);month(p.period);if(p.period<=previous)throw Error('Maanden moeten uniek en chronologisch zijn.');previous=p.period;if(!['draft','closed','published'].includes(p.stage)||(index<doc.periods.length-1&&p.stage==='draft'))throw Error('Alleen de laatste maand kan concept zijn.');if(p.published_hash&&!/^[a-f0-9]{64}$/.test(p.published_hash))throw Error('Ongeldige publicatiereferentie.');object(p.inputs,['vlag','wijzigingen','milestones','beslissing','volgende'],['milestones'],'Maandinvoer');for(const k of ['vlag','wijzigingen','beslissing','volgende'])if(Object.hasOwn(p.inputs,k)&&typeof p.inputs[k]!=='string')throw Error('Tekst verwacht: '+k);if(!Array.isArray(p.inputs.milestones)||!p.inputs.milestones.length||p.inputs.milestones.length>1000)throw Error('Verwacht 1–1000 milestones.');const ids=new Set();p.inputs.milestones.forEach(r=>{object(r,[...c.columns.map(x=>x.id),'forecast_md'],['nr','milestone','status'],'Milestone');if(!Number.isSafeInteger(r.nr))throw Error('Formuliernummer moet een JSON-geheel getal zijn.');const n=id(r.nr);if(ids.has(n))throw Error('Dubbele milestonenummers.');ids.add(n);for(const [k,v] of Object.entries(r))if(k!=='nr'&&v!==null&&!['string','number'].includes(typeof v))throw Error('Ongeldige veldstructuur: '+k);});if(!Array.isArray(p.confirmed)||new Set(p.confirmed).size!==p.confirmed.length||p.confirmed.some(n=>!Number.isSafeInteger(n)||!ids.has(n)))throw Error('Ongeldige bevestigde rijen.');object(p.tracking,['scope_changes','assume_on_plan','corrections','legacy_ack','future_factor'],[],'Meetinvoer');trackingShape(p.tracking);});return doc;}
function parse(raw,c){if(new TextEncoder().encode(raw).length>c.maxBytes)throw Error('Bestand is te groot.');let i=0;const white=()=>{while(/\s/.test(raw[i]||'')&&i<raw.length)i++;};function string(){const begin=i++;while(i<raw.length){if(raw[i]==='\\'){i+=2;continue;}if(raw[i++]==='"')return JSON.parse(raw.slice(begin,i));}throw Error('Onvolledige JSON-tekst.');}function value(depth){if(depth>50)throw Error('Bestand is te diep genest.');white();if(raw[i]==='{'){i++;white();const seen=new Set();if(raw[i]==='}'){i++;return;}while(true){white();if(raw[i]!=='"')throw Error('JSON-sleutel verwacht.');const key=string();if(seen.has(key))throw Error('Dubbele JSON-sleutel: '+key);seen.add(key);white();if(raw[i++]!==':')throw Error('JSON-dubbelepunt verwacht.');value(depth+1);white();const ch=raw[i++];if(ch==='}')return;if(ch!==',')throw Error('Ongeldig JSON-object.');}}if(raw[i]==='['){i++;white();if(raw[i]===']'){i++;return;}while(true){value(depth+1);white();const ch=raw[i++];if(ch===']')return;if(ch!==',')throw Error('Ongeldige JSON-lijst.');}}if(raw[i]==='"'){string();return;}const m=raw.slice(i).match(/^(?:true|false|null|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)/);if(!m)throw Error('Ongeldige JSON-waarde.');i+=m[0].length;}value(0);white();if(i!==raw.length)throw Error('Extra inhoud na projectbestand.');return upgrade(JSON.parse(raw),c);}
function canonicalChange(v){object(v,['id','month','decision','milestones'],['id','month','decision','milestones'],'Scopebesluit');text(v.id,'Besluit-id');month(v.month);object(v.decision,['by','date','source'],['by','date','source'],'Beslissing');text(v.decision.by,'Beslisser');text(v.decision.source,'Besluitbron');if(!/^\d{4}-\d{2}-\d{2}$/.test(v.decision.date)||new Date(v.decision.date+'T00:00:00Z').toISOString().slice(0,10)!==v.decision.date||v.decision.date.slice(0,7)!==v.month)throw Error('Scope wordt zichtbaar in de goedkeuringsmaand.');if(!Array.isArray(v.milestones)||!v.milestones.length)throw Error('Toegevoegde milestones ontbreken.');return {id:v.id,month:v.month,decision:{by:v.decision.by,date:v.decision.date,source:v.decision.source},milestones:v.milestones.map(r=>{object(r,['nr','milestone','weight_md'],['nr','milestone','weight_md'],'Toevoeging');return {nr:id(r.nr),milestone:text(r.milestone,'Naam milestone'),weight_md:number(r.weight_md,'Vast scopegewicht',true)};}).sort((a,b)=>a.nr-b.nr)};}
function evaluate(doc,c){doc=upgrade(doc,c);const base=baseline(doc.baseline),total=add(...base.milestones.map(r=>r.planned_md));const states=[];let changes=[],old=null;
 for(const p of doc.periods){const errors=[],notes=[];try{
  if(p.period<base.plan[0].period)throw Error('Rapport ligt vóór de oorspronkelijke planning.');
  if(p.tracking.assume_on_plan!==undefined&&typeof p.tracking.assume_on_plan!=='boolean')throw Error('Ongeldige aannamekeuze.');
  const added=p.tracking.scope_changes||[];if(!Array.isArray(added))throw Error('Scopebesluiten moeten een lijst zijn.');
  for(const raw of added){const change=canonicalChange(raw),known=changes.find(v=>v.id===change.id);if(known){if(JSON.stringify(known)!==JSON.stringify(change))throw Error('Bestaand scopebesluit gewijzigd.');continue;}if(change.month>p.period||change.month<base.plan[0].period||(old&&change.month<=old.period))throw Error('Scopebesluit wijzigt oudere maanden of ligt in de toekomst.');changes.push(change);}
  changes.sort((a,b)=>a.month.localeCompare(b.month)||a.id.localeCompare(b.id));
  const weights=new Map(base.milestones.map(r=>[r.nr,{weight:r.planned_md,planned:r.planned_md,added:false}]));for(const change of changes)for(const r of change.milestones){if(weights.has(r.nr))throw Error('Milestonenummer hergebruikt in scopebesluit.');weights.set(r.nr,{weight:r.weight_md,planned:'0',added:true});}
  const corrections=p.tracking.corrections||[];if(!Array.isArray(corrections))throw Error('Correcties moeten een lijst zijn.');const reasons=new Map();for(const r of corrections){object(r,['nr','reason'],['nr','reason'],'Correctie');const n=id(r.nr);if(reasons.has(n)||!weights.has(n))throw Error('Dubbele of onbekende correctie.');reasons.set(n,text(r.reason,'Correctiereden'));}
  const rows=[],missingRemaining=[];for(const r of p.inputs.milestones){const n=id(r.nr),w=weights.get(n);if(!w)throw Error('Milestone '+n+' mist een goedgekeurd scopebesluit.');text(r.milestone,'Milestone '+n+' naam');const status=text(r.status,'Milestone '+n+' voortgang');if(!c.progress.some(v=>v.value===status))errors.push('Milestone '+n+': kies de voortgang.');if(!c.health.some(h=>h.value===r.gezondheid))errors.push('Milestone '+n+': kies de gezondheid.');const done=c.tracking.delivered.includes(status),backlog=c.tracking.backlog.includes(status),closed=(c.tracking.closed||[]).includes(status);const actual=decimal(r.actual_md,'Milestone '+n+' Actual');let remaining=decimal(r.remaining_md,'Milestone '+n+' Remaining');const supplied=decimal(r.baseline_md,'Milestone '+n+' Baseline');
   if(done||closed){if(remaining!==null&&remaining!=='0')errors.push('Milestone '+n+': afgesloten maar Remaining is niet nul.');if(remaining===null)remaining='0';}
   else if(remaining===null){if(backlog&&!w.added&&w.planned!=='0')remaining=w.planned;else missingRemaining.push({text:'Milestone '+n+': Remaining ontbreekt; onbekend is niet nul.',added:w.added});}
   else if(remaining==='0')errors.push('Milestone '+n+': Remaining nul zonder oplevering; verduidelijk.');
   const baseline=w.weight,expected=actual!==null&&remaining!==null?add(actual,remaining):null;if(supplied!==null&&compare(supplied,baseline)!==0)notes.push('Milestone '+n+': ingevulde Baseline '+supplied+' genegeerd; Baseline is de oorspronkelijke inschatting ('+baseline+') en wijzigt niet.');
   const previous=old?.rows.find(x=>x.nr===n);if(previous?.delivered&&!done)errors.push('Milestone '+n+' was al opgeleverd; heropening vraagt review.');if(previous?.actual_md!==null&&previous?.actual_md!==undefined&&actual!==null&&compare(actual,previous.actual_md)<0&&!reasons.has(n))errors.push('Milestone '+n+': Actual gedaald; voeg correctiereden toe.');
   rows.push({nr:n,milestone:r.milestone,status:r.status,delivered:done,closed,weight_md:w.weight,actual_md:actual,remaining_md:remaining,baseline_md:baseline,expected_md:expected,backlog});
  }
  if(rows.length!==weights.size)throw Error('Er ontbreken goedgekeurde milestones; niet stilzwijgend verwijderen.');
  const delivered=add(...rows.filter(r=>r.delivered).map(r=>r.weight_md));let estimated=0;for(const r of rows){if(r.delivered)estimated+=Number(r.weight_md);else if(r.closed)continue;else if(r.actual_md===null||r.remaining_md===null||add(r.actual_md,r.remaining_md)==='0'){estimated=null;break;}else estimated+=Number(r.weight_md)*Number(r.actual_md)/Number(add(r.actual_md,r.remaining_md));}
  const actual=rows.some(r=>r.actual_md===null)?null:add(...rows.map(r=>r.actual_md));
  let period_actual_md=null,gained='0',lost='0',known=true;for(const r of rows){const before=old?.rows.find(x=>x.nr===r.nr);if(r.actual_md===null||(before&&before.actual_md===null)){known=false;break;}const was=before?before.actual_md:'0';if(compare(r.actual_md,was)>=0)gained=add(gained,subtract(r.actual_md,was));else lost=add(lost,subtract(was,r.actual_md));}
  if(known)period_actual_md=compare(gained,lost)>=0?subtract(gained,lost):'-'+subtract(lost,gained);
  if(period_actual_md===null)notes.push('Inzet in de rapportmaand onbekend: Actual van deze of de vorige stand ontbreekt.');else if(period_actual_md.startsWith('-'))notes.push('Inzet in de rapportmaand is negatief ('+period_actual_md+' md) door een correctie van Actual.');const point=base.plan.find(v=>v.period===p.period),assume=delivered==='0'&&!states.some(s=>s.metrics&&s.metrics.delivered_md!=='0')&&estimated===null&&!!point;let assumed=null;
  if(assume){assumed=point.scope_md;notes.push('Nog niets opgeleverd en geen volledige Actual/Remaining: aanname volgens plan, geen gemeten voortgang.');}
  for(const q of missingRemaining)if(!assume||q.added)errors.push(q.text);
  if(!c.health.some(h=>h.value===p.inputs.vlag))errors.push('Kies de projectgezondheid.');
  if(actual===null)notes.push('Totale inzet onbekend: niet alle Actual-waarden zijn ingevuld.');
  const metrics={delivered_md:delivered,estimated_md:estimated,approved_md:add(...[...weights.values()].map(w=>w.weight)),actual_md:actual,assumed_md:assumed,scope_denominator_md:total,budget_md:base.budget_md,done:rows.every(r=>r.delivered||r.closed)};
  const planned=normalizePlan(p.planning,p.period);errors.push(...planned.errors);const planning=planned.errors.length?null:planned.rows;let planning_summary=null;if(planning!==null){const planned_remaining_md=add(...planning.map(r=>r.effort_md)),remaining_md=rows.some(r=>r.remaining_md===null)?null:add(...rows.map(r=>r.remaining_md));let difference_md=null;if(remaining_md!==null)difference_md=compare(planned_remaining_md,remaining_md)>=0?subtract(planned_remaining_md,remaining_md):'-'+subtract(remaining_md,planned_remaining_md);planning_summary={planned_remaining_md,remaining_md,end_total_md:actual===null?null:add(actual,planned_remaining_md),difference_md};if(difference_md!==null&&difference_md!=='0')notes.push('Resterende maandplanning: '+planned_remaining_md+' md; Remaining volgens milestones: '+remaining_md+' md. Verschil: '+difference_md+' md. Controleer planning of inschatting; niets automatisch verdeeld.');}
  /* Mirrors tracking.prepare: ratio expected/Baseline over delivered and running milestones; factor for backlog in the projection. */
  const measured=rows.filter(r=>!r.backlog);let effort_ratio=null;if(measured.length&&measured.every(r=>r.expected_md!==null)){const bl=Number(add('0',...measured.map(r=>r.baseline_md)));if(bl)effort_ratio=Number(add('0',...measured.map(r=>r.expected_md)))/bl;}
  const choice=p.tracking.future_factor;let future_factor=1;if(choice==='ratio'){if(effort_ratio===null)notes.push('Gemeten ratio verwacht/Baseline is nog onbekend; backlog wordt met factor 1 geprojecteerd.');else future_factor=effort_ratio;}else if(choice!==undefined&&choice!==null){const value=decimal(choice,'Factor voor toekomstig werk');if(value===null||value==='0')errors.push('Factor voor toekomstig werk moet positief zijn.');else future_factor=Number(value);}
  const state={period:p.period,rows,metrics,errors,notes,planning,planning_summary,period_actual_md,effort_ratio,future_factor,scope_changes:copy(changes)};states.push(state);if(errors.length)break;old=state;
 }catch(e){states.push({period:p.period,rows:[],metrics:null,errors:[e.message],notes:[]});break;}}
 return {baseline:base,states};
}
/* Mirrors monthly_planning.cumulative: planned effort is spread over open work in proportion to Remaining,
   so expected scope = estimated + (approved-estimated) * min(1, planned/remaining). */
function projectedRemaining(state){const rows=state.rows;if(rows.some(r=>r.remaining_md===null))return null;const plain=add('0',...rows.filter(r=>!r.backlog).map(r=>r.remaining_md)),back=add('0',...rows.filter(r=>r.backlog).map(r=>r.remaining_md)),factor=state.future_factor??1;if(factor===1||back==='0')return add(plain,back);return decimal(String(Math.floor((Number(plain)+Number(back)*factor)*10+0.5)/10));}
function forwardProjection(planning,state){const m=state?.metrics;if(!m||!planning)return [];const remaining=projectedRemaining(state),est=m.estimated_md,approved=Number(m.approved_md);let total=m.actual_md,planned='0';
 return planning.map(r=>{const e=r.effort_md;planned=planned===null||e===null?null:add(planned,e);total=total===null||e===null?null:add(total,e);const open=planned===null||remaining===null?null:compare(remaining,planned)>0?subtract(remaining,planned):'0';let scope=null;if(planned!==null&&remaining!==null&&est!==null)scope=remaining==='0'?approved:Number(est)+(approved-Number(est))*Math.min(1,Number(planned)/Number(remaining));return {period:r.period,effort_md:e,total_md:total,open_md:open,scope_md:scope};});}
function newPeriod(doc,when,c){doc=upgrade(doc,c);const evaluated=evaluate(doc,c),p=doc.periods.at(-1),s=evaluated.states.at(-1);if(s.period!==p.period||s.errors.length)throw Error('Los de cijfercontroles op vóór een nieuwe maand.');month(when);if(when<=p.period)throw Error('De nieuwe maand moet later liggen.');const result=copy(doc);result.periods.at(-1).stage=p.stage==='published'?'published':'closed';const rows=copy(p.inputs.milestones);for(const row of rows)delete row.baseline_md;result.periods.push({period:when,inputs:{milestones:rows,vlag:p.inputs.vlag||''},tracking:Object.hasOwn(p.tracking,'future_factor')?{future_factor:p.tracking.future_factor}:{},confirmed:[],stage:'draft',planning:futurePlan(doc.baseline,when,p.planning)});return result;}
g.AIECModel={copy,blank,decimal,add,subtract,compare,scaled,coupledRemaining,forwardProjection,projectedRemaining,id,month,nextMonth,months,baseline,baselineFromMonths,baselineMonths,futurePlan,normalizePlan,validate,upgrade,parse,evaluate,newPeriod};
})(globalThis);
